help:
	python main_experiment.py -h

pilot7:
	python main_experiment.py -r 0 -db ~/scratch crowbrain_pilot7_test $(aws)

pilot7_live:
	python main_experiment.py -l -usa -db /raw_data/pilot7 crowbrain_pilot7 $(aws)
