help:
	python main_experiment.py -h

pilot8:
	python main_experiment.py -r 0 -db ~/scratch crowbrain_pilot8_test $(aws)

pilot8_live:
	python main_experiment.py -l -usa -db /raw_data/pilot8 crowbrain_pilot8 $(aws)
